###
POST http://127.0.0.1:8787/message?token=fdndf
Content-Type: application/json

{
   "touser" : "@all",
   "msgtype" : "text",
   "agentid" : 1000002,
   "text" : {
       "content" : "hello"
   }
}
